In [80]:
import pandas as pd
import numpy as np

In [113]:
df = pd.read_csv("../data/youtube/dataset.csv")

C:\Users\ASM EL Masrya\AppData\Local\Temp\ipykernel_7548\3902940432.py:1: DtypeWarning: Columns (6) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("../data/youtube/dataset.csv")

# Uniqueness

In [114]:
no_dup = df.drop_duplicates()

In [115]:
unique_videos = no_dup.drop_duplicates(subset=["video_id"])

In [116]:
# no_dup.sort_values(by="is_trending", ascending=False).drop_duplicates(subset=["video_id"], keep="first")

# Info

In [117]:
unique_videos.head()

,video_id,title,publishedAt,channelId,channelTitle,categoryId,trending_date,tags,view_count,likes,...,chapter_count,chapters,playability_status,supports_miniplayer,card_count,cards,is_verified,badge_labels,has_paid_promotion,comments_disabled
0,G4M_621v1As,college farewell video#trending #viralshorts,2025-04-12T02:06:42Z,UC7k_7IF3s3TY-cowwxs_yWw,Vk_07_rider,22.0,2025-11-08,"college farewell video, DDU farewell video, fa...",125784084.0,1557178.0,...,0.0,[],OK,True,1.0,"[{'teaser_text': 'الاطّلاع على التصحيحَين', 's...",False,[],False,False
1,z2voqo_Jhx4,Busking in Manchester 🇬🇧 #blindfaith #guitar #...,2025-04-06T11:35:53Z,UCM_9JHB3xXPSzJfTkD86AtA,Leonardo Patrick,10.0,2025-11-08,NaN,94744011.0,925529.0,...,0.0,[],OK,True,1.0,"[{'teaser_text': 'الاطّلاع على التصحيحَين', 's...",False,[],False,False
2,jHIt9oHFLsw,This is what happens when you play Star Wars i...,2025-04-06T10:07:12Z,UC4YyKY5o60Kckk-GXOnhT2g,Violin Phonix,22.0,2025-11-08,NaN,61945818.0,1067412.0,...,0.0,[],OK,True,1.0,"[{'teaser_text': 'الاطّلاع على التصحيحَين', 's...",True,['قناة الفنّان الرسمية'],False,False
3,gwRqLbWqKlM,LISA - FUTW (YouTube Music Nights Special Stag...,2025-03-19T03:29:33Z,UC6-BgjsBa5R3PZQ_kZ8hKPg,LLOUD Official,10.0,2025-11-08,"Blackpink, Lisa, Music, Fashion, K-Pop, kpop, ...",14555963.0,455816.0,...,0.0,[],OK,True,1.0,"[{'teaser_text': 'الاطّلاع على التصحيحَين', 's...",True,['قناة الفنّان الرسمية'],False,False
4,prpRoyrutcE,Uljhi hai yeh kis jaal me tu…. Bengaluru ❤️,2025-04-14T10:17:58Z,UCiFXnvi8ESDukE25ol2foWQ,Mr.KiranJ,10.0,2025-11-08,NaN,26204942.0,336267.0,...,0.0,[],OK,True,1.0,"[{'teaser_text': 'الاطّلاع على التصحيحَين', 's...",True,['تم إثبات الملكية'],False,False

In [118]:
unique_videos.info()

<class 'pandas.core.frame.DataFrame'>
Index: 190915 entries, 0 to 391090
Data columns (total 37 columns):
 #   Column                                    Non-Null Count   Dtype
---  ------                                    --------------   -----
 0   video_id                                  190915 non-null  object
 1   title                                     190915 non-null  object
 2   publishedAt                               190915 non-null  object
 3   channelId                                 190915 non-null  object
 4   channelTitle                              190915 non-null  object
 5   categoryId                                190915 non-null  float64
 6   trending_date                             35796 non-null   object
 7   tags                                      119066 non-null  object
 8   view_count                                190892 non-null  float64
 9   likes                                     190770 non-null  float64
 10  comment_count                             190867 non-null  float64
 11  thumbnail_link                            190915 non-null  object
 12  description                               148771 non-null  object
 13  is_trending                               190915 non-null  int64
 14  defaultLanguage                           183454 non-null  object
 15  duration                                  183450 non-null  object
 16  dimension                                 183454 non-null  object
 17  definition                                183454 non-null  object
 18  caption                                   183454 non-null  object
 19  licensedContent                           183454 non-null  object
 20  projection                                183454 non-null  object
 21  embeddable                                183454 non-null  object
 22  madeForKids                               183454 non-null  object
 23  favoriteCount                             183454 non-null  float64
 24  contentDetails.regionRestriction.blocked  9367 non-null    object
 25  contentDetails.regionRestriction.allowed  3610 non-null    object
 26  contentDetails.contentRating.ytRating     254 non-null     object
 27  chapter_count                             186148 non-null  float64
 28  chapters                                  186148 non-null  object
 29  playability_status                        186148 non-null  object
 30  supports_miniplayer                       186148 non-null  object
 31  card_count                                186148 non-null  float64
 32  cards                                     186148 non-null  object
 33  is_verified                               186148 non-null  object
 34  badge_labels                              186148 non-null  object
 35  has_paid_promotion                        186148 non-null  object
 36  comments_disabled                         190881 non-null  object
dtypes: float64(7), int64(1), object(29)
memory usage: 55.3+ MB

In [119]:
unique_videos.describe()

,categoryId,view_count,likes,comment_count,is_trending,favoriteCount,chapter_count,card_count
count,190915.000000,1.908920e+05,1.907700e+05,1.908670e+05,190915.000000,183454.0,186148.000000,186148.000000
mean,21.236996,8.343575e+06,1.581203e+05,2.129324e+03,0.182270,0.0,0.987827,0.027510
std,6.264864,5.632930e+07,7.151850e+05,3.037718e+04,0.386068,0.0,3.990665,0.163566
min,1.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.0,0.000000,0.000000
25%,20.000000,1.393095e+05,1.934000e+03,3.300000e+01,0.000000,0.0,0.000000,0.000000
50%,22.000000,5.565105e+05,1.457650e+04,3.060000e+02,0.000000,0.0,0.000000,0.000000
75%,24.000000,2.681506e+06,6.727875e+04,1.344000e+03,0.000000,0.0,0.000000,0.000000
max,30.000000,4.168919e+09,4.337832e+07,1.048303e+07,1.000000,0.0,133.000000,1.000000

In [120]:
unique_videos.columns

Index(['video_id', 'title', 'publishedAt', 'channelId', 'channelTitle',
       'categoryId', 'trending_date', 'tags', 'view_count', 'likes',
       'comment_count', 'thumbnail_link', 'description', 'is_trending',
       'defaultLanguage', 'duration', 'dimension', 'definition', 'caption',
       'licensedContent', 'projection', 'embeddable', 'madeForKids',
       'favoriteCount', 'contentDetails.regionRestriction.blocked',
       'contentDetails.regionRestriction.allowed',
       'contentDetails.contentRating.ytRating', 'chapter_count', 'chapters',
       'playability_status', 'supports_miniplayer', 'card_count', 'cards',
       'is_verified', 'badge_labels', 'has_paid_promotion',
       'comments_disabled'],
      dtype='object')

# Accuracy

In [133]:
unique_videos = unique_videos[
    unique_videos["likes"] <= unique_videos["view_count"]
]

# Drop Unnecessary Columns

In [155]:
# thoughts: channelid : remove? replace with percentange?
new_df = unique_videos.drop(columns=["thumbnail_link", "chapters", "cards", "badge_labels","contentDetails.contentRating.ytRating","contentDetails.regionRestriction.allowed","contentDetails.regionRestriction.blocked","trending_date","favoriteCount"])

# Fix Columns

## Tags to empty list

In [156]:
def process_tags(x):
    if isinstance(x, list):
        return x
    
    if pd.isna(x):
        return []
    
    if isinstance(x, str):
        x = x.strip()
        
        if x.startswith("[") and x.endswith("]"):
            x = x[1:-1]
        
        return [tag.strip() for tag in x.split(",") if tag.strip()]
    
    return []

new_df["tags"] = new_df["tags"].apply(process_tags)

In [157]:
new_df[new_df["tags"].apply(lambda x: x == [])]["tags"].count()

71079

## Description to empty string

In [158]:
new_df["description"] = new_df["description"].fillna("").astype(str)

## Comment count misisng values

In [159]:
comments_disabled_bool = new_df["comments_disabled"].map(lambda x: str(x).lower() == "true")

new_df.loc[
    new_df["comment_count"].isna() & comments_disabled_bool,
    "comment_count"
] = 0

In [161]:
new_df = new_df[new_df["comment_count"].notna()]

In [162]:
new_df.isna().sum()

video_id                  0
title                     0
publishedAt               0
channelId                 0
channelTitle              0
categoryId                0
tags                      0
view_count                0
likes                     0
comment_count             0
description               0
is_trending               0
defaultLanguage        7258
duration               7258
dimension              7258
definition             7258
caption                7258
licensedContent        7258
projection             7258
embeddable             7258
madeForKids            7258
chapter_count          4732
playability_status     4732
supports_miniplayer    4732
card_count             4732
is_verified            4732
has_paid_promotion     4732
comments_disabled        10
dtype: int64